---
# pre-commit autoupdate

fail_fast: false # true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      # - id: no-commit-to-branch
      #   args: [--branch, main, --branch, dev, --branch, uat, --branch, prd, --branch, master]


  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: \.(py)$
        args: [--settings-path=pyproject.toml]
